/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorVendorLayoutRouteImport } from './routes/vendor/_vendorLayout'
import { Route as AdminAdminLayoutRouteImport } from './routes/admin/_adminLayout'
import { Route as rootRootLayoutRouteImport } from './routes/(root)/_rootLayout'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as VendorVendorLayoutIndexRouteImport } from './routes/vendor/_vendorLayout/index'
import { Route as AdminAdminLayoutIndexRouteImport } from './routes/admin/_adminLayout/index'
import { Route as rootRootLayoutIndexRouteImport } from './routes/(root)/_rootLayout/index'
import { Route as AdminAdminLayoutProductsRouteImport } from './routes/admin/_adminLayout/products'
import { Route as rootRootLayoutTermsRouteImport } from './routes/(root)/_rootLayout/terms'
import { Route as rootRootLayoutSearchRouteImport } from './routes/(root)/_rootLayout/search'
import { Route as rootRootLayoutPrivacyRouteImport } from './routes/(root)/_rootLayout/privacy'
import { Route as rootRootLayoutCookiesRouteImport } from './routes/(root)/_rootLayout/cookies'
import { Route as rootRootLayoutContactRouteImport } from './routes/(root)/_rootLayout/contact'
import { Route as rootRootLayoutAuthenticatedRouteImport } from './routes/(root)/_rootLayout/_authenticated'
import { Route as VendorVendorLayoutWalletIndexRouteImport } from './routes/vendor/_vendorLayout/wallet/index'
import { Route as VendorVendorLayoutSettingsIndexRouteImport } from './routes/vendor/_vendorLayout/settings/index'
import { Route as VendorVendorLayoutProductsIndexRouteImport } from './routes/vendor/_vendorLayout/products/index'
import { Route as VendorVendorLayoutOrdersIndexRouteImport } from './routes/vendor/_vendorLayout/orders/index'
import { Route as VendorVendorLayoutAccountIndexRouteImport } from './routes/vendor/_vendorLayout/account/index'
import { Route as AdminAdminLayoutAccountIndexRouteImport } from './routes/admin/_adminLayout/account/index'
import { Route as rootRootLayoutVendorsIndexRouteImport } from './routes/(root)/_rootLayout/vendors/index'
import { Route as rootRootLayoutProductsIndexRouteImport } from './routes/(root)/_rootLayout/products/index'
import { Route as rootRootLayoutCategoriesIndexRouteImport } from './routes/(root)/_rootLayout/categories/index'
import { Route as rootRootLayoutCartIndexRouteImport } from './routes/(root)/_rootLayout/cart/index'
import { Route as VendorVendorLayoutProductsNewRouteImport } from './routes/vendor/_vendorLayout/products/new'
import { Route as VendorVendorLayoutProductsSlugRouteImport } from './routes/vendor/_vendorLayout/products/$slug'
import { Route as VendorVendorLayoutOrdersOrderIdRouteImport } from './routes/vendor/_vendorLayout/orders/$orderId'
import { Route as rootRootLayoutVendorsSlugRouteImport } from './routes/(root)/_rootLayout/vendors/$slug'
import { Route as rootRootLayoutProductsSlugRouteImport } from './routes/(root)/_rootLayout/products/$slug'
import { Route as rootRootLayoutCategoriesSlugRouteImport } from './routes/(root)/_rootLayout/categories/$slug'
import { Route as authAuthVendorRegisterRouteImport } from './routes/(auth)/_auth/vendor/register'
import { Route as authAuthVendorLoginRouteImport } from './routes/(auth)/_auth/vendor/login'
import { Route as authAuthAdminResetPasswordRouteImport } from './routes/(auth)/_auth/admin/reset-password'
import { Route as authAuthAdminRegisterRouteImport } from './routes/(auth)/_auth/admin/register'
import { Route as authAuthAdminLoginRouteImport } from './routes/(auth)/_auth/admin/login'
import { Route as authAuthAdminForgotPasswordRouteImport } from './routes/(auth)/_auth/admin/forgot-password'
import { Route as authAuthrootSignupRouteImport } from './routes/(auth)/_auth/(root)/signup'
import { Route as authAuthrootResetPasswordRouteImport } from './routes/(auth)/_auth/(root)/reset-password'
import { Route as authAuthrootLoginRouteImport } from './routes/(auth)/_auth/(root)/login'
import { Route as authAuthrootForgotPasswordRouteImport } from './routes/(auth)/_auth/(root)/forgot-password'
import { Route as rootRootLayoutAuthenticatedOrdersIndexRouteImport } from './routes/(root)/_rootLayout/_authenticated/orders/index'
import { Route as rootRootLayoutAuthenticatedCheckoutIndexRouteImport } from './routes/(root)/_rootLayout/_authenticated/checkout/index'
import { Route as rootRootLayoutAuthenticatedAccountIndexRouteImport } from './routes/(root)/_rootLayout/_authenticated/account/index'
import { Route as rootRootLayoutAuthenticatedOrdersOrderIdRouteImport } from './routes/(root)/_rootLayout/_authenticated/orders/$orderId'
import { Route as rootRootLayoutAuthenticatedCheckoutPaymentStatusRouteImport } from './routes/(root)/_rootLayout/_authenticated/checkout/payment-status'

const VendorVendorLayoutRoute = VendorVendorLayoutRouteImport.update({
  id: '/vendor/_vendorLayout',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLayoutRoute = AdminAdminLayoutRouteImport.update({
  id: '/admin/_adminLayout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRootLayoutRoute = rootRootLayoutRouteImport.update({
  id: '/(root)/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorLayoutIndexRoute = VendorVendorLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorVendorLayoutRoute,
} as any)
const AdminAdminLayoutIndexRoute = AdminAdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminLayoutRoute,
} as any)
const rootRootLayoutIndexRoute = rootRootLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const AdminAdminLayoutProductsRoute =
  AdminAdminLayoutProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)
const rootRootLayoutTermsRoute = rootRootLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutSearchRoute = rootRootLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutPrivacyRoute = rootRootLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutCookiesRoute = rootRootLayoutCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutContactRoute = rootRootLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutAuthenticatedRoute =
  rootRootLayoutAuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const VendorVendorLayoutWalletIndexRoute =
  VendorVendorLayoutWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const VendorVendorLayoutSettingsIndexRoute =
  VendorVendorLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const VendorVendorLayoutProductsIndexRoute =
  VendorVendorLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const VendorVendorLayoutOrdersIndexRoute =
  VendorVendorLayoutOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const VendorVendorLayoutAccountIndexRoute =
  VendorVendorLayoutAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const AdminAdminLayoutAccountIndexRoute =
  AdminAdminLayoutAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)
const rootRootLayoutVendorsIndexRoute =
  rootRootLayoutVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutProductsIndexRoute =
  rootRootLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutCategoriesIndexRoute =
  rootRootLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutCartIndexRoute = rootRootLayoutCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const VendorVendorLayoutProductsNewRoute =
  VendorVendorLayoutProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const VendorVendorLayoutProductsSlugRoute =
  VendorVendorLayoutProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const VendorVendorLayoutOrdersOrderIdRoute =
  VendorVendorLayoutOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => VendorVendorLayoutRoute,
  } as any)
const rootRootLayoutVendorsSlugRoute =
  rootRootLayoutVendorsSlugRouteImport.update({
    id: '/vendors/$slug',
    path: '/vendors/$slug',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutProductsSlugRoute =
  rootRootLayoutProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutCategoriesSlugRoute =
  rootRootLayoutCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const authAuthVendorRegisterRoute = authAuthVendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthVendorLoginRoute = authAuthVendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAdminResetPasswordRoute =
  authAuthAdminResetPasswordRouteImport.update({
    id: '/admin/reset-password',
    path: '/admin/reset-password',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthAdminRegisterRoute = authAuthAdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAdminLoginRoute = authAuthAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAdminForgotPasswordRoute =
  authAuthAdminForgotPasswordRouteImport.update({
    id: '/admin/forgot-password',
    path: '/admin/forgot-password',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthrootSignupRoute = authAuthrootSignupRouteImport.update({
  id: '/(root)/signup',
  path: '/signup',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthrootResetPasswordRoute =
  authAuthrootResetPasswordRouteImport.update({
    id: '/(root)/reset-password',
    path: '/reset-password',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthrootLoginRoute = authAuthrootLoginRouteImport.update({
  id: '/(root)/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthrootForgotPasswordRoute =
  authAuthrootForgotPasswordRouteImport.update({
    id: '/(root)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authAuthRoute,
  } as any)
const rootRootLayoutAuthenticatedOrdersIndexRoute =
  rootRootLayoutAuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedCheckoutIndexRoute =
  rootRootLayoutAuthenticatedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedAccountIndexRoute =
  rootRootLayoutAuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedOrdersOrderIdRoute =
  rootRootLayoutAuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute =
  rootRootLayoutAuthenticatedCheckoutPaymentStatusRouteImport.update({
    id: '/checkout/payment-status',
    path: '/checkout/payment-status',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminAdminLayoutRouteWithChildren
  '/vendor': typeof VendorVendorLayoutRouteWithChildren
  '/contact': typeof rootRootLayoutContactRoute
  '/cookies': typeof rootRootLayoutCookiesRoute
  '/privacy': typeof rootRootLayoutPrivacyRoute
  '/search': typeof rootRootLayoutSearchRoute
  '/terms': typeof rootRootLayoutTermsRoute
  '/admin/products': typeof AdminAdminLayoutProductsRoute
  '/': typeof rootRootLayoutIndexRoute
  '/admin/': typeof AdminAdminLayoutIndexRoute
  '/vendor/': typeof VendorVendorLayoutIndexRoute
  '/forgot-password': typeof authAuthrootForgotPasswordRoute
  '/login': typeof authAuthrootLoginRoute
  '/reset-password': typeof authAuthrootResetPasswordRoute
  '/signup': typeof authAuthrootSignupRoute
  '/admin/forgot-password': typeof authAuthAdminForgotPasswordRoute
  '/admin/login': typeof authAuthAdminLoginRoute
  '/admin/register': typeof authAuthAdminRegisterRoute
  '/admin/reset-password': typeof authAuthAdminResetPasswordRoute
  '/vendor/login': typeof authAuthVendorLoginRoute
  '/vendor/register': typeof authAuthVendorRegisterRoute
  '/categories/$slug': typeof rootRootLayoutCategoriesSlugRoute
  '/products/$slug': typeof rootRootLayoutProductsSlugRoute
  '/vendors/$slug': typeof rootRootLayoutVendorsSlugRoute
  '/vendor/orders/$orderId': typeof VendorVendorLayoutOrdersOrderIdRoute
  '/vendor/products/$slug': typeof VendorVendorLayoutProductsSlugRoute
  '/vendor/products/new': typeof VendorVendorLayoutProductsNewRoute
  '/cart/': typeof rootRootLayoutCartIndexRoute
  '/categories/': typeof rootRootLayoutCategoriesIndexRoute
  '/products/': typeof rootRootLayoutProductsIndexRoute
  '/vendors/': typeof rootRootLayoutVendorsIndexRoute
  '/admin/account/': typeof AdminAdminLayoutAccountIndexRoute
  '/vendor/account/': typeof VendorVendorLayoutAccountIndexRoute
  '/vendor/orders/': typeof VendorVendorLayoutOrdersIndexRoute
  '/vendor/products/': typeof VendorVendorLayoutProductsIndexRoute
  '/vendor/settings/': typeof VendorVendorLayoutSettingsIndexRoute
  '/vendor/wallet/': typeof VendorVendorLayoutWalletIndexRoute
  '/checkout/payment-status': typeof rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute
  '/orders/$orderId': typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  '/account/': typeof rootRootLayoutAuthenticatedAccountIndexRoute
  '/checkout/': typeof rootRootLayoutAuthenticatedCheckoutIndexRoute
  '/orders/': typeof rootRootLayoutAuthenticatedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/contact': typeof rootRootLayoutContactRoute
  '/cookies': typeof rootRootLayoutCookiesRoute
  '/privacy': typeof rootRootLayoutPrivacyRoute
  '/search': typeof rootRootLayoutSearchRoute
  '/terms': typeof rootRootLayoutTermsRoute
  '/admin/products': typeof AdminAdminLayoutProductsRoute
  '/': typeof rootRootLayoutIndexRoute
  '/admin': typeof AdminAdminLayoutIndexRoute
  '/vendor': typeof VendorVendorLayoutIndexRoute
  '/forgot-password': typeof authAuthrootForgotPasswordRoute
  '/login': typeof authAuthrootLoginRoute
  '/reset-password': typeof authAuthrootResetPasswordRoute
  '/signup': typeof authAuthrootSignupRoute
  '/admin/forgot-password': typeof authAuthAdminForgotPasswordRoute
  '/admin/login': typeof authAuthAdminLoginRoute
  '/admin/register': typeof authAuthAdminRegisterRoute
  '/admin/reset-password': typeof authAuthAdminResetPasswordRoute
  '/vendor/login': typeof authAuthVendorLoginRoute
  '/vendor/register': typeof authAuthVendorRegisterRoute
  '/categories/$slug': typeof rootRootLayoutCategoriesSlugRoute
  '/products/$slug': typeof rootRootLayoutProductsSlugRoute
  '/vendors/$slug': typeof rootRootLayoutVendorsSlugRoute
  '/vendor/orders/$orderId': typeof VendorVendorLayoutOrdersOrderIdRoute
  '/vendor/products/$slug': typeof VendorVendorLayoutProductsSlugRoute
  '/vendor/products/new': typeof VendorVendorLayoutProductsNewRoute
  '/cart': typeof rootRootLayoutCartIndexRoute
  '/categories': typeof rootRootLayoutCategoriesIndexRoute
  '/products': typeof rootRootLayoutProductsIndexRoute
  '/vendors': typeof rootRootLayoutVendorsIndexRoute
  '/admin/account': typeof AdminAdminLayoutAccountIndexRoute
  '/vendor/account': typeof VendorVendorLayoutAccountIndexRoute
  '/vendor/orders': typeof VendorVendorLayoutOrdersIndexRoute
  '/vendor/products': typeof VendorVendorLayoutProductsIndexRoute
  '/vendor/settings': typeof VendorVendorLayoutSettingsIndexRoute
  '/vendor/wallet': typeof VendorVendorLayoutWalletIndexRoute
  '/checkout/payment-status': typeof rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute
  '/orders/$orderId': typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  '/account': typeof rootRootLayoutAuthenticatedAccountIndexRoute
  '/checkout': typeof rootRootLayoutAuthenticatedCheckoutIndexRoute
  '/orders': typeof rootRootLayoutAuthenticatedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(root)/_rootLayout': typeof rootRootLayoutRouteWithChildren
  '/admin/_adminLayout': typeof AdminAdminLayoutRouteWithChildren
  '/vendor/_vendorLayout': typeof VendorVendorLayoutRouteWithChildren
  '/(root)/_rootLayout/_authenticated': typeof rootRootLayoutAuthenticatedRouteWithChildren
  '/(root)/_rootLayout/contact': typeof rootRootLayoutContactRoute
  '/(root)/_rootLayout/cookies': typeof rootRootLayoutCookiesRoute
  '/(root)/_rootLayout/privacy': typeof rootRootLayoutPrivacyRoute
  '/(root)/_rootLayout/search': typeof rootRootLayoutSearchRoute
  '/(root)/_rootLayout/terms': typeof rootRootLayoutTermsRoute
  '/admin/_adminLayout/products': typeof AdminAdminLayoutProductsRoute
  '/(root)/_rootLayout/': typeof rootRootLayoutIndexRoute
  '/admin/_adminLayout/': typeof AdminAdminLayoutIndexRoute
  '/vendor/_vendorLayout/': typeof VendorVendorLayoutIndexRoute
  '/(auth)/_auth/(root)/forgot-password': typeof authAuthrootForgotPasswordRoute
  '/(auth)/_auth/(root)/login': typeof authAuthrootLoginRoute
  '/(auth)/_auth/(root)/reset-password': typeof authAuthrootResetPasswordRoute
  '/(auth)/_auth/(root)/signup': typeof authAuthrootSignupRoute
  '/(auth)/_auth/admin/forgot-password': typeof authAuthAdminForgotPasswordRoute
  '/(auth)/_auth/admin/login': typeof authAuthAdminLoginRoute
  '/(auth)/_auth/admin/register': typeof authAuthAdminRegisterRoute
  '/(auth)/_auth/admin/reset-password': typeof authAuthAdminResetPasswordRoute
  '/(auth)/_auth/vendor/login': typeof authAuthVendorLoginRoute
  '/(auth)/_auth/vendor/register': typeof authAuthVendorRegisterRoute
  '/(root)/_rootLayout/categories/$slug': typeof rootRootLayoutCategoriesSlugRoute
  '/(root)/_rootLayout/products/$slug': typeof rootRootLayoutProductsSlugRoute
  '/(root)/_rootLayout/vendors/$slug': typeof rootRootLayoutVendorsSlugRoute
  '/vendor/_vendorLayout/orders/$orderId': typeof VendorVendorLayoutOrdersOrderIdRoute
  '/vendor/_vendorLayout/products/$slug': typeof VendorVendorLayoutProductsSlugRoute
  '/vendor/_vendorLayout/products/new': typeof VendorVendorLayoutProductsNewRoute
  '/(root)/_rootLayout/cart/': typeof rootRootLayoutCartIndexRoute
  '/(root)/_rootLayout/categories/': typeof rootRootLayoutCategoriesIndexRoute
  '/(root)/_rootLayout/products/': typeof rootRootLayoutProductsIndexRoute
  '/(root)/_rootLayout/vendors/': typeof rootRootLayoutVendorsIndexRoute
  '/admin/_adminLayout/account/': typeof AdminAdminLayoutAccountIndexRoute
  '/vendor/_vendorLayout/account/': typeof VendorVendorLayoutAccountIndexRoute
  '/vendor/_vendorLayout/orders/': typeof VendorVendorLayoutOrdersIndexRoute
  '/vendor/_vendorLayout/products/': typeof VendorVendorLayoutProductsIndexRoute
  '/vendor/_vendorLayout/settings/': typeof VendorVendorLayoutSettingsIndexRoute
  '/vendor/_vendorLayout/wallet/': typeof VendorVendorLayoutWalletIndexRoute
  '/(root)/_rootLayout/_authenticated/checkout/payment-status': typeof rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute
  '/(root)/_rootLayout/_authenticated/orders/$orderId': typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  '/(root)/_rootLayout/_authenticated/account/': typeof rootRootLayoutAuthenticatedAccountIndexRoute
  '/(root)/_rootLayout/_authenticated/checkout/': typeof rootRootLayoutAuthenticatedCheckoutIndexRoute
  '/(root)/_rootLayout/_authenticated/orders/': typeof rootRootLayoutAuthenticatedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/vendor'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/products'
    | '/'
    | '/admin/'
    | '/vendor/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/register'
    | '/admin/reset-password'
    | '/vendor/login'
    | '/vendor/register'
    | '/categories/$slug'
    | '/products/$slug'
    | '/vendors/$slug'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$slug'
    | '/vendor/products/new'
    | '/cart/'
    | '/categories/'
    | '/products/'
    | '/vendors/'
    | '/admin/account/'
    | '/vendor/account/'
    | '/vendor/orders/'
    | '/vendor/products/'
    | '/vendor/settings/'
    | '/vendor/wallet/'
    | '/checkout/payment-status'
    | '/orders/$orderId'
    | '/account/'
    | '/checkout/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/products'
    | '/'
    | '/admin'
    | '/vendor'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/register'
    | '/admin/reset-password'
    | '/vendor/login'
    | '/vendor/register'
    | '/categories/$slug'
    | '/products/$slug'
    | '/vendors/$slug'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$slug'
    | '/vendor/products/new'
    | '/cart'
    | '/categories'
    | '/products'
    | '/vendors'
    | '/admin/account'
    | '/vendor/account'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/vendor/wallet'
    | '/checkout/payment-status'
    | '/orders/$orderId'
    | '/account'
    | '/checkout'
    | '/orders'
  id:
    | '__root__'
    | '/(auth)/_auth'
    | '/(root)/_rootLayout'
    | '/admin/_adminLayout'
    | '/vendor/_vendorLayout'
    | '/(root)/_rootLayout/_authenticated'
    | '/(root)/_rootLayout/contact'
    | '/(root)/_rootLayout/cookies'
    | '/(root)/_rootLayout/privacy'
    | '/(root)/_rootLayout/search'
    | '/(root)/_rootLayout/terms'
    | '/admin/_adminLayout/products'
    | '/(root)/_rootLayout/'
    | '/admin/_adminLayout/'
    | '/vendor/_vendorLayout/'
    | '/(auth)/_auth/(root)/forgot-password'
    | '/(auth)/_auth/(root)/login'
    | '/(auth)/_auth/(root)/reset-password'
    | '/(auth)/_auth/(root)/signup'
    | '/(auth)/_auth/admin/forgot-password'
    | '/(auth)/_auth/admin/login'
    | '/(auth)/_auth/admin/register'
    | '/(auth)/_auth/admin/reset-password'
    | '/(auth)/_auth/vendor/login'
    | '/(auth)/_auth/vendor/register'
    | '/(root)/_rootLayout/categories/$slug'
    | '/(root)/_rootLayout/products/$slug'
    | '/(root)/_rootLayout/vendors/$slug'
    | '/vendor/_vendorLayout/orders/$orderId'
    | '/vendor/_vendorLayout/products/$slug'
    | '/vendor/_vendorLayout/products/new'
    | '/(root)/_rootLayout/cart/'
    | '/(root)/_rootLayout/categories/'
    | '/(root)/_rootLayout/products/'
    | '/(root)/_rootLayout/vendors/'
    | '/admin/_adminLayout/account/'
    | '/vendor/_vendorLayout/account/'
    | '/vendor/_vendorLayout/orders/'
    | '/vendor/_vendorLayout/products/'
    | '/vendor/_vendorLayout/settings/'
    | '/vendor/_vendorLayout/wallet/'
    | '/(root)/_rootLayout/_authenticated/checkout/payment-status'
    | '/(root)/_rootLayout/_authenticated/orders/$orderId'
    | '/(root)/_rootLayout/_authenticated/account/'
    | '/(root)/_rootLayout/_authenticated/checkout/'
    | '/(root)/_rootLayout/_authenticated/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  rootRootLayoutRoute: typeof rootRootLayoutRouteWithChildren
  AdminAdminLayoutRoute: typeof AdminAdminLayoutRouteWithChildren
  VendorVendorLayoutRoute: typeof VendorVendorLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor/_vendorLayout': {
      id: '/vendor/_vendorLayout'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorVendorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_adminLayout': {
      id: '/admin/_adminLayout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/_rootLayout': {
      id: '/(root)/_rootLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRootLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/_vendorLayout/': {
      id: '/vendor/_vendorLayout/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorVendorLayoutIndexRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/admin/_adminLayout/': {
      id: '/admin/_adminLayout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminLayoutIndexRouteImport
      parentRoute: typeof AdminAdminLayoutRoute
    }
    '/(root)/_rootLayout/': {
      id: '/(root)/_rootLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootRootLayoutIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/admin/_adminLayout/products': {
      id: '/admin/_adminLayout/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminLayoutProductsRouteImport
      parentRoute: typeof AdminAdminLayoutRoute
    }
    '/(root)/_rootLayout/terms': {
      id: '/(root)/_rootLayout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof rootRootLayoutTermsRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/search': {
      id: '/(root)/_rootLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof rootRootLayoutSearchRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/privacy': {
      id: '/(root)/_rootLayout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof rootRootLayoutPrivacyRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/cookies': {
      id: '/(root)/_rootLayout/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof rootRootLayoutCookiesRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/contact': {
      id: '/(root)/_rootLayout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof rootRootLayoutContactRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/_authenticated': {
      id: '/(root)/_rootLayout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRootLayoutAuthenticatedRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/vendor/_vendorLayout/wallet/': {
      id: '/vendor/_vendorLayout/wallet/'
      path: '/wallet'
      fullPath: '/vendor/wallet/'
      preLoaderRoute: typeof VendorVendorLayoutWalletIndexRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/vendor/_vendorLayout/settings/': {
      id: '/vendor/_vendorLayout/settings/'
      path: '/settings'
      fullPath: '/vendor/settings/'
      preLoaderRoute: typeof VendorVendorLayoutSettingsIndexRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/vendor/_vendorLayout/products/': {
      id: '/vendor/_vendorLayout/products/'
      path: '/products'
      fullPath: '/vendor/products/'
      preLoaderRoute: typeof VendorVendorLayoutProductsIndexRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/vendor/_vendorLayout/orders/': {
      id: '/vendor/_vendorLayout/orders/'
      path: '/orders'
      fullPath: '/vendor/orders/'
      preLoaderRoute: typeof VendorVendorLayoutOrdersIndexRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/vendor/_vendorLayout/account/': {
      id: '/vendor/_vendorLayout/account/'
      path: '/account'
      fullPath: '/vendor/account/'
      preLoaderRoute: typeof VendorVendorLayoutAccountIndexRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/admin/_adminLayout/account/': {
      id: '/admin/_adminLayout/account/'
      path: '/account'
      fullPath: '/admin/account/'
      preLoaderRoute: typeof AdminAdminLayoutAccountIndexRouteImport
      parentRoute: typeof AdminAdminLayoutRoute
    }
    '/(root)/_rootLayout/vendors/': {
      id: '/(root)/_rootLayout/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof rootRootLayoutVendorsIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/products/': {
      id: '/(root)/_rootLayout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof rootRootLayoutProductsIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/categories/': {
      id: '/(root)/_rootLayout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof rootRootLayoutCategoriesIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/cart/': {
      id: '/(root)/_rootLayout/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof rootRootLayoutCartIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/vendor/_vendorLayout/products/new': {
      id: '/vendor/_vendorLayout/products/new'
      path: '/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorVendorLayoutProductsNewRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/vendor/_vendorLayout/products/$slug': {
      id: '/vendor/_vendorLayout/products/$slug'
      path: '/products/$slug'
      fullPath: '/vendor/products/$slug'
      preLoaderRoute: typeof VendorVendorLayoutProductsSlugRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/vendor/_vendorLayout/orders/$orderId': {
      id: '/vendor/_vendorLayout/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/vendor/orders/$orderId'
      preLoaderRoute: typeof VendorVendorLayoutOrdersOrderIdRouteImport
      parentRoute: typeof VendorVendorLayoutRoute
    }
    '/(root)/_rootLayout/vendors/$slug': {
      id: '/(root)/_rootLayout/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof rootRootLayoutVendorsSlugRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/products/$slug': {
      id: '/(root)/_rootLayout/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof rootRootLayoutProductsSlugRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/categories/$slug': {
      id: '/(root)/_rootLayout/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof rootRootLayoutCategoriesSlugRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(auth)/_auth/vendor/register': {
      id: '/(auth)/_auth/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof authAuthVendorRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/vendor/login': {
      id: '/(auth)/_auth/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof authAuthVendorLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/reset-password': {
      id: '/(auth)/_auth/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof authAuthAdminResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/register': {
      id: '/(auth)/_auth/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof authAuthAdminRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/login': {
      id: '/(auth)/_auth/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof authAuthAdminLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/forgot-password': {
      id: '/(auth)/_auth/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof authAuthAdminForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/(root)/signup': {
      id: '/(auth)/_auth/(root)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthrootSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/(root)/reset-password': {
      id: '/(auth)/_auth/(root)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authAuthrootResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/(root)/login': {
      id: '/(auth)/_auth/(root)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthrootLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/(root)/forgot-password': {
      id: '/(auth)/_auth/(root)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthrootForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(root)/_rootLayout/_authenticated/orders/': {
      id: '/(root)/_rootLayout/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedOrdersIndexRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/checkout/': {
      id: '/(root)/_rootLayout/_authenticated/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/account/': {
      id: '/(root)/_rootLayout/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedAccountIndexRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/orders/$orderId': {
      id: '/(root)/_rootLayout/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/checkout/payment-status': {
      id: '/(root)/_rootLayout/_authenticated/checkout/payment-status'
      path: '/checkout/payment-status'
      fullPath: '/checkout/payment-status'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedCheckoutPaymentStatusRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthrootForgotPasswordRoute: typeof authAuthrootForgotPasswordRoute
  authAuthrootLoginRoute: typeof authAuthrootLoginRoute
  authAuthrootResetPasswordRoute: typeof authAuthrootResetPasswordRoute
  authAuthrootSignupRoute: typeof authAuthrootSignupRoute
  authAuthAdminForgotPasswordRoute: typeof authAuthAdminForgotPasswordRoute
  authAuthAdminLoginRoute: typeof authAuthAdminLoginRoute
  authAuthAdminRegisterRoute: typeof authAuthAdminRegisterRoute
  authAuthAdminResetPasswordRoute: typeof authAuthAdminResetPasswordRoute
  authAuthVendorLoginRoute: typeof authAuthVendorLoginRoute
  authAuthVendorRegisterRoute: typeof authAuthVendorRegisterRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthrootForgotPasswordRoute: authAuthrootForgotPasswordRoute,
  authAuthrootLoginRoute: authAuthrootLoginRoute,
  authAuthrootResetPasswordRoute: authAuthrootResetPasswordRoute,
  authAuthrootSignupRoute: authAuthrootSignupRoute,
  authAuthAdminForgotPasswordRoute: authAuthAdminForgotPasswordRoute,
  authAuthAdminLoginRoute: authAuthAdminLoginRoute,
  authAuthAdminRegisterRoute: authAuthAdminRegisterRoute,
  authAuthAdminResetPasswordRoute: authAuthAdminResetPasswordRoute,
  authAuthVendorLoginRoute: authAuthVendorLoginRoute,
  authAuthVendorRegisterRoute: authAuthVendorRegisterRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface rootRootLayoutAuthenticatedRouteChildren {
  rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute: typeof rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute
  rootRootLayoutAuthenticatedOrdersOrderIdRoute: typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  rootRootLayoutAuthenticatedAccountIndexRoute: typeof rootRootLayoutAuthenticatedAccountIndexRoute
  rootRootLayoutAuthenticatedCheckoutIndexRoute: typeof rootRootLayoutAuthenticatedCheckoutIndexRoute
  rootRootLayoutAuthenticatedOrdersIndexRoute: typeof rootRootLayoutAuthenticatedOrdersIndexRoute
}

const rootRootLayoutAuthenticatedRouteChildren: rootRootLayoutAuthenticatedRouteChildren =
  {
    rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute:
      rootRootLayoutAuthenticatedCheckoutPaymentStatusRoute,
    rootRootLayoutAuthenticatedOrdersOrderIdRoute:
      rootRootLayoutAuthenticatedOrdersOrderIdRoute,
    rootRootLayoutAuthenticatedAccountIndexRoute:
      rootRootLayoutAuthenticatedAccountIndexRoute,
    rootRootLayoutAuthenticatedCheckoutIndexRoute:
      rootRootLayoutAuthenticatedCheckoutIndexRoute,
    rootRootLayoutAuthenticatedOrdersIndexRoute:
      rootRootLayoutAuthenticatedOrdersIndexRoute,
  }

const rootRootLayoutAuthenticatedRouteWithChildren =
  rootRootLayoutAuthenticatedRoute._addFileChildren(
    rootRootLayoutAuthenticatedRouteChildren,
  )

interface rootRootLayoutRouteChildren {
  rootRootLayoutAuthenticatedRoute: typeof rootRootLayoutAuthenticatedRouteWithChildren
  rootRootLayoutContactRoute: typeof rootRootLayoutContactRoute
  rootRootLayoutCookiesRoute: typeof rootRootLayoutCookiesRoute
  rootRootLayoutPrivacyRoute: typeof rootRootLayoutPrivacyRoute
  rootRootLayoutSearchRoute: typeof rootRootLayoutSearchRoute
  rootRootLayoutTermsRoute: typeof rootRootLayoutTermsRoute
  rootRootLayoutIndexRoute: typeof rootRootLayoutIndexRoute
  rootRootLayoutCategoriesSlugRoute: typeof rootRootLayoutCategoriesSlugRoute
  rootRootLayoutProductsSlugRoute: typeof rootRootLayoutProductsSlugRoute
  rootRootLayoutVendorsSlugRoute: typeof rootRootLayoutVendorsSlugRoute
  rootRootLayoutCartIndexRoute: typeof rootRootLayoutCartIndexRoute
  rootRootLayoutCategoriesIndexRoute: typeof rootRootLayoutCategoriesIndexRoute
  rootRootLayoutProductsIndexRoute: typeof rootRootLayoutProductsIndexRoute
  rootRootLayoutVendorsIndexRoute: typeof rootRootLayoutVendorsIndexRoute
}

const rootRootLayoutRouteChildren: rootRootLayoutRouteChildren = {
  rootRootLayoutAuthenticatedRoute:
    rootRootLayoutAuthenticatedRouteWithChildren,
  rootRootLayoutContactRoute: rootRootLayoutContactRoute,
  rootRootLayoutCookiesRoute: rootRootLayoutCookiesRoute,
  rootRootLayoutPrivacyRoute: rootRootLayoutPrivacyRoute,
  rootRootLayoutSearchRoute: rootRootLayoutSearchRoute,
  rootRootLayoutTermsRoute: rootRootLayoutTermsRoute,
  rootRootLayoutIndexRoute: rootRootLayoutIndexRoute,
  rootRootLayoutCategoriesSlugRoute: rootRootLayoutCategoriesSlugRoute,
  rootRootLayoutProductsSlugRoute: rootRootLayoutProductsSlugRoute,
  rootRootLayoutVendorsSlugRoute: rootRootLayoutVendorsSlugRoute,
  rootRootLayoutCartIndexRoute: rootRootLayoutCartIndexRoute,
  rootRootLayoutCategoriesIndexRoute: rootRootLayoutCategoriesIndexRoute,
  rootRootLayoutProductsIndexRoute: rootRootLayoutProductsIndexRoute,
  rootRootLayoutVendorsIndexRoute: rootRootLayoutVendorsIndexRoute,
}

const rootRootLayoutRouteWithChildren = rootRootLayoutRoute._addFileChildren(
  rootRootLayoutRouteChildren,
)

interface AdminAdminLayoutRouteChildren {
  AdminAdminLayoutProductsRoute: typeof AdminAdminLayoutProductsRoute
  AdminAdminLayoutIndexRoute: typeof AdminAdminLayoutIndexRoute
  AdminAdminLayoutAccountIndexRoute: typeof AdminAdminLayoutAccountIndexRoute
}

const AdminAdminLayoutRouteChildren: AdminAdminLayoutRouteChildren = {
  AdminAdminLayoutProductsRoute: AdminAdminLayoutProductsRoute,
  AdminAdminLayoutIndexRoute: AdminAdminLayoutIndexRoute,
  AdminAdminLayoutAccountIndexRoute: AdminAdminLayoutAccountIndexRoute,
}

const AdminAdminLayoutRouteWithChildren =
  AdminAdminLayoutRoute._addFileChildren(AdminAdminLayoutRouteChildren)

interface VendorVendorLayoutRouteChildren {
  VendorVendorLayoutIndexRoute: typeof VendorVendorLayoutIndexRoute
  VendorVendorLayoutOrdersOrderIdRoute: typeof VendorVendorLayoutOrdersOrderIdRoute
  VendorVendorLayoutProductsSlugRoute: typeof VendorVendorLayoutProductsSlugRoute
  VendorVendorLayoutProductsNewRoute: typeof VendorVendorLayoutProductsNewRoute
  VendorVendorLayoutAccountIndexRoute: typeof VendorVendorLayoutAccountIndexRoute
  VendorVendorLayoutOrdersIndexRoute: typeof VendorVendorLayoutOrdersIndexRoute
  VendorVendorLayoutProductsIndexRoute: typeof VendorVendorLayoutProductsIndexRoute
  VendorVendorLayoutSettingsIndexRoute: typeof VendorVendorLayoutSettingsIndexRoute
  VendorVendorLayoutWalletIndexRoute: typeof VendorVendorLayoutWalletIndexRoute
}

const VendorVendorLayoutRouteChildren: VendorVendorLayoutRouteChildren = {
  VendorVendorLayoutIndexRoute: VendorVendorLayoutIndexRoute,
  VendorVendorLayoutOrdersOrderIdRoute: VendorVendorLayoutOrdersOrderIdRoute,
  VendorVendorLayoutProductsSlugRoute: VendorVendorLayoutProductsSlugRoute,
  VendorVendorLayoutProductsNewRoute: VendorVendorLayoutProductsNewRoute,
  VendorVendorLayoutAccountIndexRoute: VendorVendorLayoutAccountIndexRoute,
  VendorVendorLayoutOrdersIndexRoute: VendorVendorLayoutOrdersIndexRoute,
  VendorVendorLayoutProductsIndexRoute: VendorVendorLayoutProductsIndexRoute,
  VendorVendorLayoutSettingsIndexRoute: VendorVendorLayoutSettingsIndexRoute,
  VendorVendorLayoutWalletIndexRoute: VendorVendorLayoutWalletIndexRoute,
}

const VendorVendorLayoutRouteWithChildren =
  VendorVendorLayoutRoute._addFileChildren(VendorVendorLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  rootRootLayoutRoute: rootRootLayoutRouteWithChildren,
  AdminAdminLayoutRoute: AdminAdminLayoutRouteWithChildren,
  VendorVendorLayoutRoute: VendorVendorLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
