name: Next.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install PNPM correctly
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9 # or your project version

      # Setup Node and enable PNPM cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Vite.js app
        run: pnpm run build
